DROP TABLE IF EXISTS Event_Ticket;
DROP TABLE IF EXISTS Ticket_Tier;
DROP TABLE IF EXISTS Tickets;
DROP TABLE IF EXISTS Event_Categorie;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Tiers;
DROP TABLE IF EXISTS Events;
