export enum ETicketTier {
  free = 'free',
  standard = 'standard',
  premium = 'premium',
  vip = 'vip',
  platinum = 'platinum',
  diamond = 'diamond',
  titanium = 'titanium',
  elite = 'elite',
  exclusive = 'exclusive',
  limited = 'limited',
  special = 'special',
  deluxe = 'deluxe',
  ultimate = 'ultimate',
  supreme = 'supreme',
}
